version: '3'


services:
  server_a:
    image: nginx:latest
    ports:
      - "8081:80"

  server_b:
    image: nginx:latest
    ports:
      - "8082:80"

  server_c:
    image: nginx:latest
    ports:
      - "8083:80"